spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: vPocHzokBhXj5gJmNTgTFiEad998xLtG
            scope: openid,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8181/realms/sso-test/protocol/openid-connect/auth
            token-uri: http://localhost:8181/realms/sso-test/protocol/openid-connect/token
            user-info-uri: http://localhost:8181/realms/sso-test/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8181/realms/sso-test/protocol/openid-connect/certs
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8082
  servlet: 
    context-path: /ui-one
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8080/myAccount?email=happy@example.com
              
